name: Symfony CI/CD
on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mailhog:
                image: mailhog/mailhog
                ports:
                    - 1025:1025
                    - 8025:8025

        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  #   extensions: mbstring, intl, pdo, pdo_mysql, zip, xml, curl, json
                  #   ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
                  #   coverage: xdebug

            - name: Install dependencies
              run: |
                  composer install --prefer-dist --no-progress --no-suggest --no-interaction
            - name: Run tests
              run: |
                  php bin/phpunit --testdox
