name: Symfony CI/CD
on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mailhog:
                image: mailhog/mailhog
                ports:
                    - 1025:1025
                    - 8025:8025

        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  #   extensions: mbstring, intl, pdo, pdo_mysql, zip, xml, curl, json
                  #   ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
                  #   coverage: xdebug

            - name: Install dependencies
              run: |
                  composer install --prefer-dist --no-progress --no-suggest --no-interaction
            - name: Run tests
              run: |
                  php bin/phpunit --testdox

    docker-build-push:
        runs-on: ubuntu-latest
        needs: build-and-test

        steps:
            - uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64

            - name: Push Docker image
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/democicd:latest
